### PR TITLE
Update naming on commit position array

### PR DESCRIPTION
**Pull request by rpkarlsson**
Updates naming to match backend.

### CODE REVIEW

**Comment by fyrkant** [comment]
We should add positions to the initialState also.

**Comment by Angamanga** [comment]
And change the naming for the matrix as well.

**Comment by rpkarlsson** [comment]
Added to initialstate. Thanks for the catch @mw222rs. 

Matrix will be a separate PR.

**Comment by Angamanga** [comment]
OK  :+1:

**Pull request merged**
