### PR TITLE
redux and react-router thrown in, small messing about with sphere

### PR DESCRIPTION
**Pull request by fyrkant**
Really fast and dirty implementation of redux and react-router (which has apparently been updated to 2.0 and is yelling in the console, but ignore that for now!). Might be alot of weird stuff to take in, maybe a front-end meeting tomorrow and run through it?

### CODE REVIEW

**Comment by mw222rs** [comment]
#1

**Comment by fyrkant** [comment]
Hehe, all tests failing, such a beautiful sight!

**Comment by fyrkant** [comment]
Oh crap, I didn't follow the workflow with a new branch... :skull:

**Comment by fyrkant** [comment]
Isn't this OK to merge now?

**Comment by fyrkant** [comment]
Even if we won't use this architecture there are some improvements to the sphere component in here!

**Comment by rpkarlsson** [comment]
I was under the impression that more work was needed as the tests are failing? And we want to make the corrections on the PR and not merge, have a failing master and then add another PR to fix master?

Would be happy to merge if the tests were green. Or if we decide its ok to merge PR's that fail the tests.

**Comment by fyrkant** [comment]
Ah, yeah sorry that's true, tests should pass! I'll fix it later today.

**Comment by fyrkant** [comment]
Oh crap, conflicts! Gimme a minute, I'll fix them and do a new commit.

**Comment by sk222sw** [comment]
I get `"throw new Error("cannot resolve path (or pattern) '" + path + "'");"` when running the tests, any clues why?

Edit: never mind, removing the single quotes from the path in `"test": "mocha ./spec/**/*-spec.js --compilers js:babel-core/register",` did the trick.

**Comment by fyrkant** [comment]
Ah, ok, maybe the quotes aren't necessary. Weird that it error'd out for you but not for me, I guess "because windows" is the answer? :grimacing:

**Comment by fyrkant** [comment]
I threw in a new PR to remove the single quotes.

**Comment by fyrkant** [comment]
Closes #3

**Pull request merged**
